### ISSUE TITLE
Switch from Data API to Responses API

### ISSUE THREAD

**Issue by picsoung** [csgillespie/rtypeform#13]
Hi @csgillespie!

Congratulations for the awesome work on this package! :)
I am Nicolas, and I just joined Typeform as a Developer Advocate, helping developers succeed using our APIs.

I have noted that your package uses the "old" Data API, instead of the new Responses API.
We should work together on a transition. Some steps are explained in our [Migration Guide](https://developer.typeform.com/responses/migrate-from-data-to-responses-api/)

And I will be delighted to help you out :)

I am very curious to hear more about use cases to use Typeform data in R. 
Cheers

**Comment by dctanugi** [comment]
How did it go, @picsoung and @csgillespie ?

**Comment by picsoung** [comment]
@dctanugi not sure anything started...
If you plan to look at it, I would be happy to help!

**Comment by csgillespie** [comment]
Not had a chance to look at it yet. On my list of things to do. Happy to collaborate.

**Comment by csgillespie** [comment]
@picsoung At https://developer.typeform.com/get-started/applications/ it states 

> In the Authorization callback URL field, type the complete callback URL for your app.

What does this mean? What should I use?

**Comment by picsoung** [comment]
Hey @csgillespie 

This callback URL is used in oAuth flow, that's where the user will be redirected once authenticated with Typeform.
For an SDK like yours you might need it, so you could just put a placeholder URL instead.

Hope it's clear
Best

**Comment by csgillespie** [comment]
So I've now spent a bit more time on this. From 
https://developer.typeform.com/get-started/scopes/

@picsoung  I get to 

https://api.typeform.com/oauth/authorize?state=xyz789&client_id={your_client_id}&redirect_uri=https://results-example.herokuapp.com/callback&scope={scope1}+{scope2}+{scope3}

I can figure out "your_client_id" and the scopes, but what should I put for the "redirect_uri"? Tried a bunch of stuff, no luck. Should it be a variation of localhost, 127.0.0.1 or jumpingrivers.com or https://github.com/csgillespie/rtypeform or ...?

---

BTW, one of my errors came to https://github.com/Typeform/results-example/issues/7 - not helpful when you can't close/solve these issues.

**Comment by picsoung** [comment]
Hey @csgillespie 

Are you familiar with oAuth flow?
our engineer Anabella wrote a nice piece about it I recommend you to take a look : https://medium.com/typeforms-engineering-blog/the-beginners-guide-to-oauth-dancing-4b8f3666de10

Basically on an oauth flow, the user is redirected to a typeform login screen where they grant your app to access their typeform account, once they agree they get redirected to the `redirect_uri`. There you will receive a temporary code you have to exchange for an access token. 

The flow is described in our doc [here](https://developer.typeform.com/get-started/applications/) with this graphic
![](https://d1g2kzh8x1k8nq.cloudfront.net/typeform-oauth-flow1.ebc9aab6.png)

So it's important that the `redirect_uri` is reachable from typeform, can't be localhost.
You can use [ngrok](https://ngrok.com/) to expose your localhost.

But for the SDK you don't need to go through the whole oauth flow to get a token, you can try it out using personal token as well. [Create one here](https://admin.typeform.com/account#/section/user)

Thank you putting out issues on our example repo, I will take a closer look.

**Comment by csgillespie** [comment]
Created a plan for movement at https://github.com/csgillespie/rtypeform/issues/14

@picsoung  What would be really helpful is if typeform could provide an example typeform (with data) that covered all question types. This would be really useful for Unit tests.

**Comment by csgillespie** [comment]
@picsoung Where should I give feedback on the API docs? For example, at https://developer.typeform.com/responses/reference/retrieve-responses/ the `page_size` parameter talks about a `pages` parameter that isn't mentioned anywhere else?

Thanks

**Comment by picsoung** [comment]
Hi @csgillespie 
Thanks for your feedback.

The way we do pagination on Typeform APIs is a bit different than other people, we don't use page numbers...

You can find examples here: https://developer.typeform.com/responses/walkthroughs/#use-query-parameters-to-retrieve-specific-data

I get that the text could be confusing, will see how we can improve it.

Feel free to email feedback directly at nicolas.grenie@typeform.com

Thanks
