### ISSUE TITLE
Error: All nested columns must have the same number of elements.

### ISSUE THREAD

**Issue by Gabriv93** [csgillespie/rtypeform#25]
Hello everyone. I always used the package rtypeform for getting responses of my type forms to elaborate them in shiny dashboard.

This morning, when from the script I run the command
`responses <- get_responses(form_id = form_id, 
                           api = api,
                           page_size = 1000)`
with my form_id and api, I get the error:
"Error: All nested columns must have the same number of elements."

I used before the version 2.0.0, when I got the error:
"Errore: lexical error: invalid char in json text.
                                       <html> 	<head> 		<meta http-equ
                     (right here) ------^"
So I updated from this GitHub repository to version 2.0.0.9003

I'm using Open 3.5.1 in Mac OS X Catalina 10.15.4

Can anyone give me some guess what's going on here?
Thank you

**Comment by Gabriv93** [comment]
The error is at this point of the function "get_responses()":

`all_answers = all_answers %>% 
              map2(question_types, ~select(.x, "field_type", "landing_id", starts_with(paste0(.y, "_")))) %>% 
              map(~unnest(.x, cols = c())) %>% 
              map(~rename(.x, type = 1, value = 3))`

when it Map unnest with cols = c()

**Comment by Gabriv93** [comment]
removing the argument cols = c() it works, making the function works modified... This issue could be useful for future development? Does it have an explanations that argument I don't understand but it's useful I'm implementing it wrong? Thanks

**Comment by csgillespie** [comment]
I can't reproduce this issue. 

1. Could you update the tidyr package, unnest comes from that package
1. Could you send me output from 
```
all_answers = all_answers %>% map2(question_types, ~select(.x, "field_type", "landing_id", starts_with(paste0(.y, "_"))))
```
1. Put in your `sessionInfo()`

**Comment by csgillespie** [comment]
Stale issue. No feedback
