### ISSUE TITLE
Via SO thread

### ISSUE THREAD

**Issue by brudis-r7** [csgillespie/rtypeform#3]
I think I'd consider returning separate components for and 100% completed and less than 100% completed answers:

    library(purrr)
    library(dplyr)

    res <- httr::GET("https://api.typeform.com/v1/form/JlCM2J",
               query=list(key="ecab3f590a2af4ca55468adc95686a043bbf6c9a"))

    httr::content(res, as="text") %>%
      jsonlite::fromJSON(simplifyVector=FALSE) -> tmp

    http_status <- tmp$http_status

    stats <- tmp$stats

    map_df(tmp$questions, flatten_df) -> questions

    keep(tmp$responses, ~.$completed ==1) %>%
      map_df(flatten_df) -> completed

    glimpse(completed)
    ## Observations: 1
    ## Variables: 35
    ## $ completed                          <chr> "1"
    ## $ token                              <chr> "b84567f64cedf2b0050eb0c209...
    ## $ browser                            <chr> "default"
    ## $ platform                           <chr> "other"
    ## $ date_land                          <chr> "2016-12-17 12:21:06"
    ## $ date_submit                        <chr> "2016-12-17 12:22:29"
    ## $ user_agent                         <chr> "Mozilla/5.0 (Windows NT 10...
    ## $ referer                            <chr> "https://gowtham11.typeform...
    ## $ network_id                         <chr> "fdebc44ea7"
    ## $ textfield_38991412                 <chr> "A"
    ## $ dropdown_38991418                  <chr> "Accounting"
    ## $ textarea_38991420                  <chr> "A"
    ## $ textfield_38991413                 <chr> "A"
    ## $ textarea_38991421                  <chr> "A"
    ## $ listimage_38991426_choice          <chr> "Company"
    ## $ textfield_38991414                 <chr> "A"
    ## $ website_38991435                   <chr> "http://A.com"
    ## $ textarea_38991422                  <chr> "A"
    ## $ listimage_38991427_choice          <chr> "Sincere"
    ## $ listimage_38991428_choice          <chr> "Male"
    ## $ list_38991436_choice               <chr> "17 or younger"
    ## $ list_38991437_choice               <chr> "Upper class"
    ## $ listimage_38991429_choice_49501105 <chr> "Store"
    ## $ listimage_38991430_choice          <chr> "Product"
    ## $ textarea_38991423                  <chr> "A"
    ## $ listimage_38991431_choice          <chr> "Techy"
    ## $ listimage_38991432_choice_49501124 <chr> "Fuchsia Rose"
    ## $ listimage_38991433_choice          <chr> "Classic"
    ## $ list_38991438_choice               <chr> "$3,000 or less"
    ## $ listimage_38991434_choice_49501140 <chr> "Brand Design"
    ## $ textarea_38991424                  <chr> "A"
    ## $ textfield_38991415                 <chr> "A"
    ## $ dropdown_38991419                  <chr> "Afghanistan"
    ## $ email_38991439                     <chr> "A@a.com"
    ## $ textarea_38991425                  <chr> "A"

    keep(tmp$responses, ~.$completed ==0) %>%
      map_df(flatten_df) -> not_completed

    glimpse(not_completed)
    ## Observations: 1
    ## Variables: 9
    ## $ completed   <chr> "0"
    ## $ token       <chr> "27181b2b95f69f0024f198194ec48561"
    ## $ browser     <chr> "default"
    ## $ platform    <chr> "other"
    ## $ date_land   <chr> "2016-12-16 04:01:40"
    ## $ date_submit <chr> "0000-00-00 00:00:00"
    ## $ user_agent  <chr> "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWe...
    ## $ referer     <chr> "https://gowtham11.typeform.com/to/JlCM2J"
    ## $ network_id  <chr> "8c7fd4d289"

You could return the 5 components as a `list()`:

    list(
      http_status=tmp$http_status,
      stats=tmp$stats,
      questions=tmp$questions,
      completed_responses=completed,
      uncompleted_responses=not_completed
    )

and give it a class name which wld enable having a special `print.class()` method for it to show the summary data and the responses in a tad nicer format.

Not sure I'd spend more time on it unless you see lots of folks using typeform for their forms.

(Just realized I hadn't logged out of the work github acct to post this. Rest assured it's @hrbrmstr)

**Comment by csgillespie** [comment]
Good idea and thanks
