### ISSUE TITLE
question more than issue

### ISSUE THREAD

**Issue by jason-yardley** [csgillespie/rtypeform#30]
ive been reading your information sheet from : https://cran.r-project.org/web/packages/rtypeform/rtypeform.pdf

i can see there is a section on Post Response which i find really interesting. 
i have a need to migrate responses from one form to another (bulk, cant do manually).
Is this something this project can do? Currently typeform do not have an api that supports this, but it may be possible with a sequence or collection of post requests in a function

Cheers

**Comment by csgillespie** [comment]
The `post_response()` function a simple wrapper around calling a post request. I'm not sure it's possible to do a bulk update (certainly not with the current version of rtypeform). 

Sorry
